ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALL_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALL_DECLINED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALL_ENDED';
